#!/usr/bin/env python3
"""
Generate supabase/seed_history.sql from validator-output/*.json.

This produces a stand-alone SQL script that, when pasted into Supabase's
SQL editor (or run via psql / supabase migration), populates pools + teams
+ team_riders + import_log for every historical year we have parsed.

Run:
    python3 tdf-pool-v2/scripts/generate_seed_sql.py
"""
from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
VOUT = REPO / "scripts" / "validator-output"
OUT = REPO / "supabase" / "seed_history.sql"


def sql_str(s: str | None) -> str:
    if s is None:
        return "null"
    return "'" + s.replace("'", "''") + "'"


HEADER = """\
-- ============================================================================
-- Historical pools seed
--
-- Populates pools, teams, team_riders, and import_log for the years we have
-- parsed from validator-output/. Generated by scripts/generate_seed_sql.py —
-- do not edit by hand. Re-run that script if the validator output changes.
--
-- Safe to re-run: every insert is idempotent via ON CONFLICT.
-- Run AFTER 0001..0005 migrations have applied.
--
-- match_status starts as 'unmatched' for everything; once you populate the
-- riders table for each pool (via PCS startlist scrape), the matcher will
-- update these rows.
-- ============================================================================

"""


def emit_year(parsed) -> str:
    year = parsed["year"]
    if not year:
        return ""
    teams = parsed["teams"]
    max_reserves = max((len(t["reserves"]) for t in teams), default=3)
    reserves_allowed = max(max_reserves, 3)

    lines: list[str] = []
    lines.append(
        f"-- Year {year} ({parsed['source']}) — {len(teams)} teams"
    )
    lines.append("do $$")
    lines.append("declare")
    lines.append("  v_pool_id uuid;")
    lines.append("  v_team_id uuid;")
    lines.append("begin")

    # 1) Pool upsert
    lines.append(
        f"  insert into public.pools (year, name, reserves_allowed, notes)\n"
        f"    values ({year}, 'Tour de France {year}', {reserves_allowed}, "
        f"{sql_str('Imported from ' + parsed['source'])})\n"
        f"    on conflict (year) do update\n"
        f"      set name = excluded.name,\n"
        f"          reserves_allowed = excluded.reserves_allowed,\n"
        f"          notes = excluded.notes\n"
        f"    returning id into v_pool_id;"
    )

    # 2) Each team: upsert teams row, wipe team_riders, then bulk-insert picks
    for team in teams:
        team_name = (
            f"{team['player']}'s {team['team_name']}".strip() or team["player"]
        )
        lines.append("")
        lines.append(f"  -- team: {team['player']}")
        lines.append(
            f"  insert into public.teams (pool_id, name, player_name, source_doc)\n"
            f"    values (v_pool_id, {sql_str(team_name)}, "
            f"{sql_str(team['player'])}, {sql_str(parsed['source'])})\n"
            f"    on conflict (pool_id, name) do update\n"
            f"      set player_name = excluded.player_name,\n"
            f"          source_doc  = excluded.source_doc\n"
            f"    returning id into v_team_id;"
        )
        lines.append("  delete from public.team_riders where team_id = v_team_id;")

        if team["riders"] or team["reserves"]:
            value_rows: list[str] = []
            for i, r in enumerate(team["riders"]):
                value_rows.append(
                    f"      (v_team_id, {sql_str(r)}, false, null, {i+1}, 'unmatched')"
                )
            for i, r in enumerate(team["reserves"]):
                value_rows.append(
                    f"      (v_team_id, {sql_str(r)}, true, {i+1}, null, 'unmatched')"
                )
            lines.append(
                "  insert into public.team_riders\n"
                "    (team_id, raw_name, is_reserve, reserve_order, pick_order, match_status)\n"
                "  values\n" + ",\n".join(value_rows) + ";"
            )

    # 3) Audit row
    unresolved = parsed.get("unresolved", [])
    details = json.dumps({"unresolved": unresolved})
    lines.append("")
    lines.append(
        f"  insert into public.import_log (pool_id, kind, message, details)\n"
        f"    values (v_pool_id, 'teams_seed',\n"
        f"            {sql_str(f'Seeded {len(teams)} teams from ' + parsed['source'])},\n"
        f"            {sql_str(details)}::jsonb);"
    )
    lines.append("end $$;")
    lines.append("")
    return "\n".join(lines) + "\n"


def main():
    parts = [HEADER]
    for path in sorted(VOUT.glob("*.json")):
        parsed = json.loads(path.read_text())
        if not parsed.get("year"):
            continue
        parts.append(emit_year(parsed))
        parts.append("")
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"Wrote {OUT}  ({OUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
